baseURL : "https://senseibara.com/"
languageCode : "en-us"
title : "Sensei Bara"
theme : "vanilla-bootstrap-hugo-theme"

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Articles
    pre: edit
    url: /articles/
    weight: 2
  - name: Tags
    pre: tag
    url: /tags/
    weight: 3
  - name: About
    pre: smile
    url: /about/
    weight: 4

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: <p class="blog_post_content">OSU! I am Sensei Bara</p> <p class="blog_post_content">I write about leadership in the context of <strong>Pop culture</strong>, ...and just culture, but mostly pop culture. </p> <p class="blog_post_content"> If you have never seen this blog before, first of all shame on you ! Second of all this would be a great place to start. </p> <p class="blog_post_content"> If you are the manual skipping type of person, then you'll find my list of articles here, go ahead.</p> <p class="blog_post_content"> If you would like to know more about me, which i know you do ! There is this page they call the about page, i chosed to call it ... The about page ! (like to be original...)</p><p class="blog_post_content"> With all that being said i'll let you </p>
  footerText: Made by Ndiaye Bara
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2