baseURL : "https://example.org/"
languageCode : "en-us"
title : "My New Hugo Site"
theme : "vanilla-bootstrap-hugo-theme"

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Articles
    pre: edit
    url: /articles/
    weight: 2
  - name: Tags
    pre: tag
    url: /tags/
    weight: 3
  - name: About
    pre: smile
    url: /about/
    weight: 4