baseURL : "https://example.org/"
languageCode : "en-us"
title : "Sensei Bara"
theme : "vanilla-bootstrap-hugo-theme"

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Articles
    pre: edit
    url: /articles/
    weight: 2
  - name: Tags
    pre: tag
    url: /tags/
    weight: 3
  - name: About
    pre: smile
    url: /about/
    weight: 4

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Welcome to sensei bara,
  footerText: Made by Ndiaye Bara
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2